name: study_planner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  provider: ^6.1.2
  table_calendar: ^3.2.0
  fl_chart: ^0.70.2
  intl: ^0.20.2
  uuid: ^4.5.1
  sqflite_common_ffi: ^2.4.0+3
  material_symbols_icons: ^4.2928.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  windows: true
  image_path: "assets/study_planner_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/Datterino.png
    - assets/San_Marzano.png
    - assets/Cuore_di_Bue.png
    - assets/icona_pomodoro.png
